######################################################################
# Automatically generated by qmake (3.0) Fri Mar 25 00:31:19 2016
######################################################################

TEMPLATE = app
TARGET = gtk
INCLUDEPATH += .

# Input
SOURCES += gtk.c qt.cpp
